### ISSUE TITLE
ExtendedCurrency object is null when trying to fetch data

### ISSUE THREAD

**Issue by ritesh-dubey** [midorikocak/currency-picker-android#2] opened 2017-10-05 16:48 UTC
Trying to fetch ExtendedCurrency object using:

`ExtendedCurrency currency = ExtendedCurrency.getCurrencyByISO("USD");`

The above code initializes currency object as null.
Can you please provide a possible solution to this issue?

**Comment by BanterClaus** [comment] 2017-11-15 16:01
Seems to be an issue with the comparator in ExtendedCurrency. No time to do a PR to fix right now but I did a quick workaround this way:

`private static ExtendedCurrency getExtendedCurrencyByISO(String code) {
        List<ExtendedCurrency> allCurrencies = ExtendedCurrency.getAllCurrencies();
        code = code.toUpperCase();
        for (ExtendedCurrency currency : allCurrencies) {
            if (currency.getCode().equals(code)) {
                return currency;
            }
        }
        return null;
    }`

**Comment by midorikocak** [comment] 2018-01-15 10:57
Thanks, I will try to reproduce it. A PR would be very good.

**Comment by ubaierbhat** [comment] 2019-01-22 20:53
This issue can be closed as it has already been fixed and does not exist in v 1.2.1

**Closed** 2019-08-26 08:09 UTC
